/* Recipes keyed by dish id. Amounts are written for the stated serving count
   and chosen so that one serving lands near that dish's entry in SEED_DISHES —
   the recipe is where the composition grams come from, so editing one should
   mean revisiting the other. `group` tags an ingredient with the food group it
   counts toward; untagged ingredients are inert or trace (spices, aromatics,
   white rice, water). */

export const RECIPES = {
  beyaynetu: {
    servings: 2,
    time: "2 h, mostly unattended",
    ingredients: [
      { item: "Teff injera", amount: "2.5 rounds (≈480 g)", group: "wholeGrains" },
      { item: "Red lentils, dry — misir wot", amount: "70 g", group: "legumes" },
      { item: "Yellow split peas, dry — kik alicha", amount: "65 g", group: "legumes" },
      { item: "Chickpea flour — shiro", amount: "35 g", group: "legumes" },
      { item: "Collard greens, raw — gomen", amount: "300 g", group: "vegetables" },
      { item: "Cabbage and carrot — tikil gomen", amount: "170 g", group: "vegetables" },
      { item: "Potato, diced", amount: "50 g", group: "tubers" },
      { item: "Onion, finely diced", amount: "200 g" },
      { item: "Niter kibbeh (spiced clarified butter)", amount: "16 g", group: "animalTropFat" },
      { item: "Neutral oil", amount: "32 g", group: "plantOils" },
      { item: "Berbere, turmeric, garlic, ginger", amount: "to taste" },
    ],
    steps: [
      "Sweat the onion dry in a wide pan until it collapses and browns, 15 minutes, before adding any oil — this is what gives the wots their depth.",
      "Split the onion three ways. For misir wot, add niter kibbeh and berbere, bloom, then the lentils and water; simmer 30 minutes to a thick stew.",
      "For kik alicha, add oil, turmeric, garlic and ginger, then the split peas and water; simmer 40 minutes until soft and pale gold.",
      "For shiro, whisk the chickpea flour into water off the heat, then cook it down with niter kibbeh and berbere for 15 minutes until it thickens and no longer tastes raw.",
      "Braise the collards with garlic until tender — 300 g raw cooks down to about two ½-cup mounds. Cook the cabbage, carrot and potato with turmeric until just soft.",
      "Line a platter with injera and spoon each stew in its own mound. Serve with extra injera for tearing.",
    ],
    note: "Sized as a restaurant platter shared by two, not a family batch: five mounds of roughly 60-75 g each per person. Onion is absorbed into the wots and already counted in their weight, so it is left untagged rather than added to vegetables twice. The niter kibbeh decides this dish's score — 8 g per person against a 5 g scaled ceiling is what binds its headroom.",
  },

  puttanesca: {
    servings: 4,
    time: "35 min",
    ingredients: [
      { item: "Dry pasta", amount: "1 lb (454 g), ~1050 g cooked", group: "refinedPasta" },
      { item: "Italian Field Roast", amount: "1 package (368 g)", group: "fieldRoast" },
      { item: "Tomatoes, tinned", amount: "28 oz (794 g)", group: "vegetables" },
      { item: "Onion, medium", amount: "150 g", group: "vegetables" },
      { item: "Kalamata olives", amount: "16 (64 g)", group: "vegetables" },
      { item: "Calabrian chillies", amount: "1.5 tbsp (22 g)", group: "vegetables" },
      { item: "Capers", amount: "2 tbsp (17 g)", group: "vegetables" },
      { item: "Garlic", amount: "15 g", group: "vegetables" },
      { item: "Parsley, basil, bay, thyme", amount: "15 g", group: "vegetables" },
      { item: "Anchovy fillets", amount: "4 small (16 g)", group: "fish" },
      { item: "Parmesan", amount: "1.5 oz (42 g), ×5 = 212 milk-eq", group: "dairy" },
      { item: "Olive oil, for cooking", amount: "45 g", group: "plantOils" },
    ],
    note: "The anchovies are the only animal item besides the parmesan, and they put this dish into fish and shellfish — 4 g per serving against a 30 g target, so it registers without straining anything. The olive oil is the one unmeasured quantity: the recipe says for cooking, and 45 g for the pan is my estimate. Olives are counted as vegetables, which understates their energy, since they are mostly fat and the vegetable density does not know that.",
  },

  sundubu: {
    servings: 4,
    time: "25 min",
    ingredients: [
      { item: "Silken tofu", amount: "1 whole tube (350 g)", group: "legumes" },
      { item: "Beyond ground, in place of the pork", amount: "80 g", group: "beyond" },
      { item: "Kimchi", amount: "3 oz (85 g)", group: "vegetables" },
      { item: "Daikon", amount: "50 g", group: "vegetables" },
      { item: "Green onions", amount: "2 (30 g)", group: "vegetables" },
      { item: "Green chili and mild red chili", amount: "35 g", group: "vegetables" },
      { item: "Yellow onion", amount: "1/4 (40 g)", group: "vegetables" },
      { item: "Minced garlic", amount: "1 tbsp (10 g)", group: "vegetables" },
      { item: "Toasted sesame oil", amount: "1/2 tbsp (7 g)", group: "plantOils" },
      { item: "Vegetable oil", amount: "1 tbsp (13 g)", group: "plantOils" },
      { item: "Veggie broth, in place of the water and bouillon", amount: "1.5 cups (360 ml)" },
      { item: "Gochugaru, soy sauce, oyster sauce, black pepper", amount: "to taste" },
      { item: "White rice, alongside", amount: "2 rice-cooker cups, ~880 g cooked", group: "whiteRice" },
    ],
    note: "The pot is eaten across four servings rather than finished in one sitting, and the rice is saved and reheated the same way — two rice-cooker cups, about 320 g uncooked and 880 g cooked, divided across those four servings at 220 g each. The tofu and kimchi amounts are as cooked; the daikon and the remaining quantities come from a reference recipe close to but not exactly this version. The eggs are left out.",
  },

  mapo: {
    servings: 4,
    time: "30 min",
    ingredients: [
      { item: "Medium-firm tofu", amount: "14 oz block (397 g)", group: "legumes" },
      { item: "Beyond, in place of the ground pork", amount: "3 oz (85 g)", group: "beyond" },
      { item: "Green peas", amount: "1/2 cup (72 g)", group: "vegetables" },
      { item: "Red and green bell pepper", amount: "1/4 each (60 g)", group: "vegetables" },
      { item: "Green onions", amount: "2 (30 g)", group: "vegetables" },
      { item: "Garlic and ginger", amount: "2 cloves + 1 tsp (14 g)", group: "vegetables" },
      { item: "Chili oil", amount: "1.5 tbsp (20 g)", group: "plantOils" },
      { item: "Vegetable oil", amount: "1 tbsp (13 g)", group: "plantOils" },
      { item: "Sichuan peppercorn oil", amount: "1/2 tbsp (7 g)", group: "plantOils" },
      { item: "Toasted sesame oil", amount: "1 tsp (4.5 g)", group: "plantOils" },
      { item: "Sugar", amount: "1 tsp (4 g)", group: "addedSugar" },
      { item: "Veggie stock, in place of the chicken stock", amount: "1 cup (240 ml)" },
      { item: "Doubanjiang, soy sauce, oyster sauce, Shaoxing, black vinegar", amount: "to taste" },
      { item: "Cornstarch slurry", amount: "1 tbsp (8 g)" },
      { item: "White rice, underneath", amount: "2 rice-cooker cups, ~880 g cooked", group: "whiteRice" },
    ],
    note: "Four separate oils come to 45 g for the pan — chili, vegetable, Sichuan peppercorn and sesame — which is 22% of the energy here and the largest single thing the earlier estimate had missed. The batch is eaten across four servings, and the rice is saved and reheated the same way — two rice-cooker cups, about 880 g cooked, divided across those four servings at 220 g each. Every quantity here is from the recipe. The doubanjiang is a fermented broad-bean paste and carries some oil of its own, counted as trace.",
  },

  chili: {
    servings: 6,
    time: "1 h 15 min",
    ingredients: [
      { item: "Beyond mince", amount: "680 g", group: "beyond" },
      { item: "Kidney, pinto and black beans, cooked", amount: "780 g", group: "legumes" },
      { item: "Hominy", amount: "390 g", group: "wholeGrains" },
      { item: "Tomatoes and tomatillos", amount: "1.1 kg", group: "vegetables" },
      { item: "Bell pepper, jalapeño, green chiles", amount: "500 g", group: "vegetables" },
      { item: "Onion", amount: "200 g", group: "vegetables" },
      { item: "Sweetcorn", amount: "-", group: "vegetables" },
      { item: "Neutral oil", amount: "48 g", group: "plantOils" },
      { item: "Sour cream and cheddar, to top", amount: "≈1.2 kg milk-eq", group: "dairy" },
      { item: "Chipotle in adobo, cumin, oregano", amount: "to taste" },
    ],
    note: "The toppings are the single largest lever here — 200 g milk-eq per serving is most of the dairy ceiling.",
  },

  gochujangTofu: {
    servings: 2,
    time: "35 min",
    ingredients: [
      { item: "Firm tofu, pressed and cubed", amount: "350 g", group: "legumes" },
      { item: "Broccoli, florets", amount: "400 g", group: "vegetables" },
      { item: "Potato starch, for dredging", amount: "40 g" },
      { item: "Neutral oil, for frying", amount: "24 g", group: "plantOils" },
      { item: "Gochujang", amount: "40 g" },
      { item: "Corn syrup or honey", amount: "24 g", group: "addedSugar" },
      { item: "Sesame seeds", amount: "10 g", group: "nuts" },
      { item: "Soy sauce, garlic, rice vinegar", amount: "to taste" },
    ],
  },

  pho: {
    servings: 1,
    time: "1 h for the broth, 5 min to assemble",
    ingredients: [
      { item: "Tofu", amount: "150 g", group: "legumes" },
      { item: "Straw mushrooms, bean sprouts, herbs and the fixins", amount: "140 g", group: "vegetables" },
      { item: "Rock sugar", amount: "5 g", group: "addedSugar" },
      { item: "Neutral oil", amount: "3 g", group: "plantOils" },
      { item: "Rice noodles", amount: "200 g cooked", group: "riceNoodles" },
      { item: "Veggie broth", amount: "700 ml" },
      { item: "Charred onion and ginger, star anise, cinnamon, clove", amount: "for the broth" },
    ],
  },

  cashewTofu: {
    servings: 1,
    time: "20 min",
    ingredients: [
      { item: "Firm tofu, cubed", amount: "180 g", group: "legumes" },
      { item: "Cashews", amount: "30 g", group: "nuts" },
      { item: "Bell pepper, celery, onion", amount: "140 g", group: "vegetables" },
      { item: "Neutral oil", amount: "20 g", group: "plantOils" },
      { item: "Sugar", amount: "10 g", group: "addedSugar" },
      { item: "Soy sauce, Shaoxing, rice vinegar, garlic", amount: "to taste" },
      { item: "White rice, alongside", amount: "200 g cooked", group: "whiteRice" },
    ],
    steps: [
      "Toast the cashews dry in the wok until they colour, then tip them out.",
      "Fry the tofu in a hot, heavily oiled wok without moving it until each face sets, then remove.",
      "Stir-fry the vegetables hard and briefly so they stay snappy.",
      "Return the tofu, add the sauce, thicken with a cornstarch slurry.",
      "Cashews in off the heat so they stay crisp.",
    ],
    note: "A restaurant wok carries far more oil than a home pan — around 20 g per order.",
  },

  vegThali: {
    servings: 1,
    time: "served as one tray",
    ingredients: [
      { item: "Dal, in a katori", amount: "150 g", group: "legumes" },
      { item: "Roti", amount: "90 g (2)", group: "wholeGrains" },
      { item: "Sabzi, in a katori", amount: "110 g", group: "vegetables" },
      { item: "Aloo", amount: "70 g", group: "tubers" },
      { item: "Raita", amount: "80 g", group: "dairy" },
      { item: "Salad", amount: "40 g", group: "vegetables" },
      { item: "Papad", amount: "2 (25 g), deep-fried" },
      { item: "Pickle and chutney", amount: "15 g" },
      { item: "White rice", amount: "150 g cooked", group: "whiteRice" },
      { item: "Ghee, on the roti and in the tadka", amount: "8 g", group: "animalTropFat" },
      { item: "Oil, across the tray and the papad", amount: "26 g", group: "plantOils" },
    ],
    steps: [
      "Dal cooked to collapse, then whisked smooth and finished with a tadka of cumin, mustard seed and curry leaf.",
      "Sabzi kept drier than the dal for contrast, with its own tadka.",
      "Aloo fried with cumin and amchur until the edges catch.",
      "Raita whisked with cucumber, salt and roasted cumin.",
      "Papad fried to order, pickle and salad plated alongside.",
      "Everything arrives at once in katoris with hot roti.",
    ],
    note: "Portions are the small katoris a thali actually comes in. Roti counts as whole grain, raita as 1× milk-eq. The papad is deep-fried and the pickle is oil-packed, so both land as plant oil without earning anything back.",
  },

  mezze: {
    servings: 1,
    time: "served as one plate",
    ingredients: [
      { item: "Hummus", amount: "80 g", group: "legumes" },
      { item: "Falafel", amount: "100 g (4)", group: "legumes" },
      { item: "Mercimek köfte", amount: "20 g", group: "legumes" },
      { item: "Salad and olives", amount: "110 g", group: "vegetables" },
      { item: "Walnut muhammara", amount: "15 g", group: "nuts" },
      { item: "Olive oil, across the plate", amount: "28 g", group: "plantOils" },
      { item: "White pita", amount: "90 g", group: "refinedBread" },
    ],
    steps: [
      "Falafel from chickpeas soaked overnight and never cooked first, blitzed coarse with onion, parsley and cumin, rested, then fried to order.",
      "Hummus blended long with ice water and tahini until it turns pale and aerated.",
      "Mercimek köfte worked from red lentils and fine bulgur with pepper paste, shaped into quenelles.",
      "Muhammara blended from roasted pepper, walnut, breadcrumb and pomegranate molasses.",
      "Plated together with the salad and olives, finished with a heavy pour of olive oil.",
    ],
    note: "The olive oil pour is the part home cooks underestimate — a mezze plate carries close to 30 g across the spreads.",
  },

  beanTacos: {
    servings: 1,
    time: "served as three tacos plus a side",
    ingredients: [
      { item: "Corn tortillas", amount: "90 g (3)", group: "wholeGrains" },
      { item: "Refried beans, side", amount: "120 g", group: "legumes" },
      { item: "Lard (manteca), in the beans", amount: "8 g", group: "animalTropFat" },
      { item: "Mexican rice, side", amount: "160 g cooked", group: "whiteRice" },
      { item: "Tomato and onion, in the rice", amount: "15 g", group: "vegetables" },
      { item: "Calabacita squash, corn, onion, tomato", amount: "120 g", group: "vegetables" },
      { item: "Crema", amount: "30 g (×2.7 = 81 milk-eq)", group: "dairy" },
      { item: "Queso fresco", amount: "12 g (×5 = 60 milk-eq)", group: "dairy" },
      { item: "Neutral oil, on the plancha and in the rice", amount: "23 g", group: "plantOils" },
      { item: "Garlic, epazote, chili", amount: "to taste" },
    ],
    steps: [
      "Squash cooked on the plancha with onion, garlic, corn and tomato until it fries rather than steams.",
      "Beans mashed and fried in rendered lard — the manteca is the point of frijoles refritos, and it is what the score turns on.",
      "Rice toasted in oil until it smells nutty, then simmered with tomato and onion.",
      "Tortillas heated on the comal until they blister and puff.",
      "Filled, then finished with crema and crumbled queso fresco.",
    ],
    note: "Corn tortillas count as whole grain via nixtamalization. Two things hide on this plate: the dairy, where crema at ×2.7 and queso fresco at ×5 come to ≈140 g milk-eq, and the lard in the beans, which breaches the animal-fat ceiling at twice over. The rice earns nothing — white rice is inert — but the oil it is fried in still counts against the plate.",
  },

  cheesePlate: {
    servings: 2,
    time: "10 min",
    ingredients: [
      { item: "Assorted cheese", amount: "180 g (×5 = 900 milk-eq)", group: "dairy" },
      { item: "Walnuts", amount: "44 g", group: "nuts" },
      { item: "Grapes", amount: "140 g", group: "fruits" },
      { item: "Wholegrain crackers", amount: "80 g", group: "wholeGrains" },
    ],
  },
};
